# Generated by Django 3.1.2 on 2020-10-02 22:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('map', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='favorite',
            name='lat',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='favorite',
            name='lng',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
